version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
